apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-waf
  annotations:
    appgw.ingress.kubernetes.io/waf-policy-for-path: "/subscriptions/fcab32af-0c4c-4720-8738-97b428ca9ff0/resourceGroups/agicdemo/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/myapp1-waf-policy1"
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: myapp1.thiruaws.com
      http:
        paths:
          - path: /app1
            pathType: Prefix
            backend:
              service:
                name: app1-nginx-clusterip-service
                port: 
                  number: 80

